### ISSUE TITLE
проблема с входом

### ISSUE THREAD

**Issue by diserof** [kmlebedev/netcitybot#3]
https://net-school.cap.ru запрашивает больше инфорации: Регион; Городской округ / Муниципальный район; Населённый пункт; Тип ОО
![netshool](https://user-images.githubusercontent.com/81841507/197624250-c3c02fdb-b11b-4e5b-a4ad-03d9b32879ea.png)

**Comment by kmlebedev** [comment]
@diserof  Готово

![Screenshot 2022-11-06 at 16 57 01](https://user-images.githubusercontent.com/9497591/200169374-59c1b19b-fa7f-44b3-acb1-187f6c89ebf8.png)
